### ISSUE TITLE
Issues with normalizeSelf() and setting magnitude

### ISSUE THREAD

**Issue by op-rt** [wblut/HE_Mesh#2]
Dear @wblut ,

I'm having issues when normalizing vectors with Hemesh. 
Looking at `WB_Vector()`, it seems `normalizeSelf()` returns the magnitude of a vector, not its normalized vector

```
@Override
	public double normalizeSelf() {
		final double d = getLength();
		if (WB_Epsilon.isZero(d)) {
			set(0, 0, 0);
		} else {
			set(xd() / d, yd() / d, zd() / d);
		}
		return d;
}
```

I believe that you're returning `d` on purpose here but then how do you get the normalized vector ?

Also, without a normalize function, I'm unable to set the magnitude of a vector (ideally `normalizeSelf()` + `scaleSelf()` would have worked). Does Hemesh have something similar to `setMag()` (Processing) or `normalizeTo()` (Toxiclibs) ? 

Would appreciate your lights.

Regards,

**Comment by wblut** [comment]
normalizeSelf() modifies the vector you run it on, hence the “Self”. So after v.normalizeSelf(), v is normalized.


To set a vector to a certain magnitude:
v.normalizeSelf();

v.mulSelf(mag);

**Comment by op-rt** [comment]
Oh dear, of course !
Thank you for the swift reply.

Best
