### ISSUE TITLE
Setting precision for getTriangulation2D()

### ISSUE THREAD

**Issue by jacbouzada** [wblut/HE_Mesh#28]
I´m working with Delaunay2D this way: `WB_Triangulation2D  triangulation = WB_Triangulate.getTriangulation2D(myPoints);`

My sketch is continuously running and recalculating the array list of points and de WB_Triangulation2D  triangulation. After some loops I get this error:

`Exception in thread "Animation Thread" com.vividsolutions.jts.triangulate.quadedge.LocateFailureException: Locate failed to converge (at edge: LINESTRING( 727.137316619485 549.9402615694925, 692.0081530014013 462.1518014376356)).  Possible causes include invalid Subdivision topology or very close sites`

I found this solution for the JTS Topology Suite that suggest that setting the tolerance to a small but non-zero tolerance (e.g. 0.0001) it seems to work.
http://sourceforge.net/p/jts-topo-suite/mailman/message/27320130/

The getTriangulation3D method (`getTriangulation3D (final List<?extends WB_Coordinate > points, final double precision`)  allows us to set a precision.  But the method `getTriangulation2D` doesn´t.
Could it be easy to include it in also the getTriangulation2D method?

Thanks !!

**Comment by wblut** [comment]
Good idea for JTS. I'll look into this.
