### ISSUE TITLE
Updating a  WB_KDTreeInteger without rebuilding it

### ISSUE THREAD

**Issue by op-rt** [wblut/HE_Mesh#3]
Apologies for the inconvenience. I'm wondering whether it is possible or not to change a KDTree without having to rebuild it. 

Basically I have an array of cells whose locations are stored in a `WB_KDTreeInteger `. These locations _may_ change over time but not at the same moment (only 1 cell out of 1000 will move, one by one). Is it possible to update the entry corresponding to the cell that has moved (update the location) without having to rebuild entirely the `WB_KDTreeInteger` at each iteration ?

**Comment by wblut** [comment]
Unfortunately, the kdtree isn’t dynamic. When you do many queries per “frame”, a rebuild can still be advantageous. If not, then it will indeed be too expensive to consider. My main use for it is to detect points close to each other when sequentially adding points, “does this point already exist”. For dynamic spatial hierarchy, I tend to resort to a fixed grid with a single bin per grid cell. Moving particles are much easier to track and the speedup can be as large as with a kdtree. I

**Comment by op-rt** [comment]
Thanks a lot for the reply and details. I'll keep rebuilding the KDTree at each frame. And I got to say, it's working pretty good so far.

Thanks again,

Respectfully
