### ISSUE TITLE
Latest build doesn't run in Processing 2, Python mode

### ISSUE THREAD

**Issue by monstrim** [wblut/HE_Mesh#45]
I've been using a version of your library that I'd gotten from google code quite a while ago. I can't seem to find it anymore; the version on archive.org is a 2010 one, and I'm pretty sure the version I had was 2014.

Anyway, I'm noticing lots of features here on github that me version doesn't seem to have, so I dowloaded the latest build here (2016-02-07), and I can't run it. Just adding add_library('hemesh') to a new sketch gives me a 'ClassNotFound Exception: colorLib.Palette' error.

I still have my old version saved, but I can't draw with textures, or use most of the utilitary vertex methods with it...

-- edit: I believe it's this one: http://web.archive.org/web/20140702012200/http://hemesh.wblut.com/
the dowload seems to feature the examples I mention in the comment below ;)

**Comment by monstrim** [comment]
By the way, I have an examples folder from a previous version, which I believe is better organized and seems to have more examples than the one featured here. Do you want it?

**Comment by wblut** [comment]
:-)

That is because the current examples are systematically being converted 
to the newer version.

Cheers,

F.

monstrim schreef op 2016-03-11 17:44:

**Comment by monstrim** [comment]
Hi there! I'm still having problems finding colorlib.Palette with the new build. Is that a new intentional dependency?

**Comment by vormplus** [comment]
You can find colorLib over here: https://github.com/vormplus/colorLib.

Haven't tested colorLib with Python mode though. Let me know if it works.

**Comment by monstrim** [comment]
It does work, thank you!
