### ISSUE TITLE
HE_Selection.selectFacesWithOtherTemporaryLabel() is documented but missing

### ISSUE THREAD

**Issue by virtualritz** [wblut/HE_Mesh#46]
See subject. It is documented but missing from HE_Selection.java in the latest release.
Breaks e.g.: http://www.wblut.com/tutorials/more/shatterstar/

**Comment by wblut** [comment]
Well spotted, an unfortunate remnant of a parallel HE_Mesh. It should be selectFacesWithOtherInternalLabel().

**Comment by virtualritz** [comment]
Don't forget to rebuild the Doxygen docs you ship too.
