### ISSUE TITLE
saveTo******Color is not working.

### ISSUE THREAD

**Issue by bizkitj** [wblut/HE_Mesh#49]
Hello 

Frist of all, thank you, Frederik Vanhoutte , thank you for such a wonderful lib.

I am trying to export the generated mesh with the color info out of processing. However, the exported model does not have any color or mtl info. I am using the latest version of Meshlab V2016.12 to view the model.

Here is the code I am testing:

`import peasy.*;
import wblut.core.*;
import wblut.geom.*;
import wblut.hemesh.*;
import wblut.math.*;
import wblut.nurbs.*;
import wblut.processing.*;

HE_Mesh [] mesh;
WB_Render render;
color [] c = new color [10];

void setup () {
  size (800, 800, P3D);
  HEC_Box box = new HEC_Box(50, 50, 50, 1, 1, 1);
  mesh = new HE_Mesh[10];

  for (int i = 0; i < mesh.length; i ++) {
    box.setCenter(i*60, 0, i*10);
    mesh[i] = new HE_Mesh(box);
  }
  render = new WB_Render(this);

  for (int i =0; i < mesh.length; i++) {
    c[i] = color(random(255), random(255), random(255));
  }
}

void draw () {
  background(25);
  pushMatrix();
  translate(width/2, height/2);
  rotateX(radians(mouseX));
  rotateY(radians(mouseY));
  for (int i =0; i<mesh.length; i++) {
    fill(c[i]);
    render.drawFaces(mesh[i]);
  }
  popMatrix();
}

void keyPressed() {
  if (key =='s') {
    HET_Export.saveToOBJWithVertexColor(mesh, sketchPath(""), "test_vertex_color");
    HET_Export.saveToOBJWithFaceColor(mesh, sketchPath(""), "test_face_color");
    HET_Export.saveToWRLWithFaceColor(mesh, sketchPath(""), "test_WRL_color");
    HET_Export.saveToPLYWithFaceColor(mesh, sketchPath(""), "test_face_color");
  }
  println("saved");
}
`

By the way, on the keyPressed function, HET_Export.saveToWRLWithFaceColor and  HET_Export.saveToPLYWithFaceColor are giving me erros. Am I missing something?

Thank you again.

**Comment by vormplus** [comment]
A first problem I've noticed: the meshes you are drawing to the screen don't have any color. When you create your mesh, you need to set the color for the faces like this:

`mesh[i].setFaceColor( color(random(255), random(255), random(255)) );`

This will set the color for all faces of your mesh. You can also set different colors for each face by looping over them.

To render the colored mesh to the screen, you need to use the `drawFacesFC()` method. This method will use the colors stored in the mesh datastructure.

`render.drawFacesFC( mesh[i] );`

The WRL and PLY export methods are also giving errors when I test them in Processing 3, so there's probably something wrong in the library.

**Comment by bizkitj** [comment]
Hi Vormplus

Thank you for the quick reply. 
With your help, I can draw the colored mesh on Porcessing screen, however, when I load the exported mesh in meshlab, it gives me something different. 

![he_mesh_2_meshlab_color](https://cloud.githubusercontent.com/assets/25093538/22200086/98268b30-e198-11e6-8ad4-024b987fcf7b.PNG)

HE_Mesh is such a wonderful lib, but lacking of document and great examples, tutorials, which makes it difficulit to use, e.g someone like me.

**Comment by vormplus** [comment]
Could be something related to meshlab. Best to try it with a single mesh, and not with 10 individual ones.

The Javadocs included with the library are a great resource, but they are quite large, so it might be difficult to find what you are looking for if you don't know the library that well.

**Comment by wblut** [comment]
Fixed in latest repo. Color export is correct in Blender, C4D and 3DS Max. It seems to be a meshLab issue.
