### ISSUE TITLE
Performance.

### ISSUE THREAD

**Issue by bizkitj** [wblut/HE_Mesh#50]
Hello again.
I am doing a performance test. Found HE_Mesh is somehow, slow. Maybe I am doing something stupid or wrong, please bear with me.

Here is the code I am running.
----------------------------Main calss----------------------------------------------------
`import peasy.*;
import peasy.*;
import wblut.core.*;
import wblut.geom.*;
import wblut.hemesh.*;
import wblut.math.*;
import wblut.nurbs.*;
import wblut.processing.*;

PeasyCam cam;
WB_Render render;
mesh m ;
P5_box p;
void setup () {
  size (800, 800, P3D);
  cam = new PeasyCam(this, 300);
  render = new WB_Render(this);
  m = new mesh(); //he_mesh box
  p = new P5_box(); //processing box
}

void draw () {
  background(25);
  m.render(); // draw HE_mesh box
  //p.render(); // draw processing box
}`
------------------------------------End of Main class------------------------------

---------------------------P5_box class----------------------------------------------
`class P5_box {

  int columns = 100, rows = 100, spacing = 60;
  float x_location, y_location;
  P5_box() {
  }

  void render() {
    stroke(0);
    for (int i =0; i < columns; i++) {
      for (int j = 0; j < rows; j++) {
        x_location = i*spacing;
        y_location = j*spacing;
        pushMatrix();
        translate(x_location,y_location,0);
        stroke(0);
        fill(200);
        box(50);
        popMatrix();
      }
    }
  }
}`
-------------------------------------------End of P5 class----------------------------------------------

--------------------------------------Mesh class---------------------------------
`class mesh {
  HE_Mesh [] mesh;
  int columns = 100, rows = 100, spacing = 60;
  HEC_Box box;
  mesh() {
    box = new HEC_Box(50, 50, 50, 1, 1, 1);
    mesh = new HE_Mesh [columns*rows];
  }

  void render() {
    stroke(0);
    for (int i =0; i < columns; i++) {
      for (int j = 0; j < rows; j++) {
        box.setCenter(i*spacing, j*spacing, 0);
        mesh[i] = new HE_Mesh(box);
        noStroke();
        fill(200);
        render.drawFaces(mesh[i]);
        stroke(0);
        render.drawEdges(mesh[i]);
        //mesh[i].clear();
      }
    }
    
---------------------------------End of Mesh class--------------------------------------------------
    //for (int i =0; i < mesh.length; i++) {
    //  render.drawFacesFC(mesh[i]);
    //}
  }
}`

**Comment by wblut** [comment]
Not a big surprise, drawing 10000 HE_Mesh objects will always be slower 
than using the Processing internally optimized box(). HE_Mesh objects 
are used for creating and can then be frozen in a Processing PShape for 
quick rendering. There is also an overhead from the quad faces of the 
mesh that need to be triangulated every frame before Processing can 
render it efficiently. It's a trivial operation but it might help slow 
things down... For generic meshes this is unavoidable, for a box it's a 
bit silly.

The other thing is that you are using box.setCenter(i_spacing, 
j_spacing, 0); every frame, in effect you are recalculating the 8 mesh 
vertices of the 10000 boxes every frame. There is no need for this.
Move the box once after creation or use Processing translate().

Cheers,

F


bizkitj schreef op 2017-01-24 11:59:

**Comment by bizkitj** [comment]
Hello wbult
Thank you for the quick reply. I am thrilled. ;).
I am not sure if this is the right place to ask. I am pretty new to Processing and your wonderful lib. I am trying to do an APP for Android via processing Android mode.

Here is the code I have at this moment.
`//Autohor Bizkit

import peasy.*;


PImage img;
int cell_size, cols, rows, resolution;
float z;
boolean export_obj;
PeasyCam cam;
void setup () {
  //fullScreen(P3D);
  size (1124, 690, P3D);
  cam = new PeasyCam(this,width/2,height/2,0,800);
  img = loadImage("D:/Processing_app/image_exercises/exercies04/data/Imagee00001.jpg");
  cell_size = 250;
  resolution = 15;
  println("Original_img_widh = " + img.width);
  println("Original_img_height = " + img.height);
  cols = width/cell_size;
  rows = height/cell_size;
  rectMode(CENTER);
  textSize(20);
}

void draw () {
  background(85);
  // text
  fill(255);
  text("cell_size is " + cell_size, 0, height, 200);
  text("Z method is B ", width/2, height, 200);
  text("Z is  " + z, width - width/5, height, 200);

  cell_size = resolution;
  cols = width/cell_size;
  rows = height/cell_size;

  //get img pixels
  img.loadPixels();
  for (int x = 0; x < cols; x++) {
    for (int y = 0; y < rows; y++) {
      int x_pos = x * cell_size + cell_size/2;
      int y_pos = y * cell_size + cell_size/2;
      int loc = x_pos + y_pos*img.width;
      color c = img.pixels[loc];
      float z_pos = map(brightness(img.pixels[loc]), 0, 255, 0, z);

      // draw 3D geom
      pushMatrix();
      translate(x_pos, y_pos, z_pos);
      fill(c);
      noStroke();
      box(cell_size, cell_size, 160);
      popMatrix();
    }
  }

}

void keyPressed() {
  if (key=='6') {
    z+=10;
  }
  if (key=='4') {
    z-=10;
  }
  if (key=='s') {
    save("test.jpg");
  }
  if (key=='k') {
    resolution++;
  }

  if (key=='l') {
    resolution--;
  }
  if (key=='j') {
    export_obj = true;
  }
}`

So, the final mesh, I am going to 3D Print it. Well, since I am pretty new to programming and processing . I am running into lots of problems.

1: The above code can not run on my Android Device. As soon as I try to run it on the device, processing console gives me error "OpenGL error 1280 at bot beginDraw(): invalid enum"
2: Because of  problem #1. I did lots of search and digging, reading. I have turned to your wonderful lib, HE_Mesh. did some tests  on my Android Device, worked. Then, I modified above code to use HE_Mesh. However, since it is going to draw LOTS of boxes, it is really really slow on desketop computer not even mentioning to run it on the Android device.

I am wondering, maybe you can give me some suggestions as for how  to make it work on Android device and running fast, lighting fast? :).

I am using Processing V3.2.3 Android SDK API 7.1.1 (25)

Thank you again for your wonderful lib, although I know little of it.

All the best
J

**Comment by wblut** [comment]
Using HE_Mesh doesn't change anything about the fact that rendering will use OpenGL. HE_Mesh does not include a rendering engine. It is purely geometry and is primarily intended to use Processing for rendering.
