### ISSUE TITLE
HE_FaceIterator does not exist.

### ISSUE THREAD

**Issue by bizkitj** [wblut/HE_Mesh#51]
Example, Tut006_Mesh_Selection, HE_FaceIterator does not exist.

Processing 3.2.3. Win 10 64.

Please help, really need this to work.

**Comment by vormplus** [comment]
Just remove this line at the end of the sketch for it to work. 

`mesh.subdivideSelected(new HES_CatmullClark(), mesh.selectFacesWithOtherInternalLabel(-1), 2);`

**Comment by wblut** [comment]
modifySelected and subdivideSelected has been removed. Modify and subdivide are now directly called from the selection. 

HE_Selection sel=mesh.selectFacesWithOtherInternalLabel(-1);
sel.subdivide(new HES_CatmullClark(),2)

**Comment by wblut** [comment]
Likewise HE_FaceIterator(mesh) is no longer a public function. It needs to be called like this:

HE_FaceIterator fItr=mesh.fItr();
