### ISSUE TITLE
Ref_HEC_FromTriangulation example doesn't work

### ISSUE THREAD

**Issue by Jagni** [wblut/HE_Mesh#53]
The method HEC_FromTriangulation() is called but it doesn't exist.

**Comment by wblut** [comment]
Can you check the HE_Mesh version you're using?
`println(WB_Version.version()`

It should be at least 5.0.0, otherwise this creator isn't included. Current version is 5.0.2.

**Comment by Jagni** [comment]
W:Blut HE_Mesh 3.0.3 Ursa Major

So it's probably just an old build I've downloaded before and forgot. Thank you!

**Comment by wblut** [comment]
Can you confirm if it works after redownloading?

**Comment by Jagni** [comment]
It works

**Comment by wblut** [comment]
Great!

Cheers,

F
