### ISSUE TITLE
Octahedron and other polyhedron code: Consider rewriting to use public domain code

### ISSUE THREAD

**Issue by peteroupc** [wblut/HE_Mesh#55]
The HEC_Octahedron and similar polyhedron code mentions being based on code from the link < http://www.cs.umbc.edu/~squire/ >; however, I think it can be replaced with public domain code (for example, code I have in my html3dutil project under demos/polyhedra.js). Note that the exact page < https://www.csee.umbc.edu/~squire/reference/reference.shtml > mentions that the code on that page is covered by the GNU General Public License (I am not a lawyer).

**Comment by wblut** [comment]
Thanks, I think I can remove the "being based on" disclaimer for these polyhedron generators. The only thing remaining are the coordinates and those are public domain.

Thanks,

Frederik

**Comment by peteroupc** [comment]
I had expected the code files in question to be rewritten to just use an array of the coordinates of the faces rather than a function that generates those coordinates, as was the case before I started this issue.

**Comment by wblut** [comment]
Aren't expectations wonderful :-)
The more general HEC_Plato, HEC_Archimedes, HEC_Catalan and HEC_Johnson 
use coordinate lists.In a next revison the 4 affected Platonic 
generators will defer to the more general HEC_Plato. But that's a 
refactor that's not high on my priority list right now.

Cheers,

Frederik

**Comment by peteroupc** [comment]
I see. Thank you for the update.
