### ISSUE TITLE
saveToOBJWithFaceColor---multi mesh does not work.

### ISSUE THREAD

**Issue by bizkitj** [wblut/HE_Mesh#58]
Hello, I am tring to export multi colored mesh, however it does not work.
When I try to export one mesh, it worked.  I am using the latest version of HE_Mesh.  I am still learning, slowly.

Here is the simple test code.

`import peasy.*;
import wblut.nurbs.*;
import wblut.hemesh.*;
import wblut.core.*;
import wblut.geom.*;
import wblut.processing.*;
import wblut.math.*;

HE_Mesh [] mesh;
WB_Render render;
PeasyCam cam;
void setup () {
  size (600, 600, P3D);
  cam = new PeasyCam(this, 300);
  HEC_Box box = new HEC_Box(50, 50, 50, 1, 1, 1);
  mesh = new HE_Mesh [1];
  for (int i=0; i<mesh.length; i++) {
    mesh[i] = new HE_Mesh(box);
    mesh[i].moveSelf(i*60, 0, 0);
    color meshColor = color (random(185), random(250), random(36));
    mesh[i].setFaceColor(meshColor);
  }

  render = new WB_Render(this);
}

void draw () {
  background(125);
  for (HE_Mesh m : mesh) {
    noStroke();
    render.drawFacesFC(m);
    stroke(0);
    render.drawEdges(m);
  }
}

void keyPressed() {
  if (key=='s') {
    final String path = "C:/Users/****/Documents/Processing/photo2mesh_HeMESH";
    HET_Export.saveToOBJWithFaceColor(mesh, path, "test_color");
    println("model saved: " + path);
  }
}
`

Screen capture of export one box, it worked.
![image](https://cloud.githubusercontent.com/assets/25093538/23575824/d2b20ae0-00ce-11e7-810f-d8de4670851b.png)

Screen capture of export 10 boxes, unfortunatelly, it does not work.
![image](https://cloud.githubusercontent.com/assets/25093538/23575847/3c0facb8-00cf-11e7-8038-feac66f1af34.png)

From the screen captures, it looks like only the 1st obj's color gets exported and the rest of the obj's color is set to the 1st obj's color.

**Comment by wblut** [comment]
When saving multiple meshes the facecounter doesn't reset properly in HET_WriterOBJ when writing the mtl file. I will fix this. In the meantime you can work around this by exporting different files.

**Comment by wblut** [comment]
Fixed in the build-of-the-day 170304 and onwards
