### ISSUE TITLE
HET_Export.saveToOBJWithFaceColor exported obj reload back,  error.

### ISSUE THREAD

**Issue by bizkitj** [wblut/HE_Mesh#59]
Hello
I have exported multiple mesh as obj, but, as soon as I re-load them back into processing, the meshes are all flipped, upside-down 

```
import peasy.*;
import wblut.nurbs.*;
import wblut.hemesh.*;
import wblut.core.*;
import wblut.geom.*;
import wblut.processing.*;
import wblut.math.*;

HE_Mesh [] mesh;
HE_Mesh objLoaded;
int columns=10, rows=10, index;
WB_Render render;
PeasyCam cam;
void setup () {
  size (600, 600, P3D);
  cam = new PeasyCam(this, 300);
  HEC_Box box = new HEC_Box(50, 50, 50, 1, 1, 1);
  mesh = new HE_Mesh [columns*rows];
  for (int i =0; i < columns; i++) {
    for (int j =0; j< rows; j++) {
      mesh[index] = new HE_Mesh(box);
      mesh[index].moveSelf(i*60, j*60, random(200));
      color meshColor = color (random(185), random(250), random(36));
      mesh[index].setFaceColor(meshColor);
      index++;
    }
  }
  HEC_FromOBJFile obj = new HEC_FromOBJFile(
    "C:/Users/****/Documents/Processing/photo2mesh_HeMESH/test_color.obj");
  objLoaded = new HE_Mesh(obj);
  //for (int i=0; i<mesh.length; i++) {
  //  mesh[i] = new HE_Mesh(box);
  //  mesh[i].moveSelf(i*60, 0, 0);
  //  color meshColor = color (random(185), random(250), random(36));
  //  mesh[i].setFaceColor(meshColor);
  //}

  render = new WB_Render(this);
}

void draw () {
  background(125);
  for (HE_Mesh m : mesh) {
    noStroke();
    render.drawFacesFC(m);
    stroke(0);
    render.drawEdges(m);
  }
  if (keyPressed) {
    noStroke();
    render.drawFacesFC(objLoaded);
    stroke(0);
    render.drawEdges(objLoaded);
  }
}

void keyPressed() {
  if (key=='s') {
    final String path = "C:/Users/jeason/Documents/Processing/photo2mesh_HeMESH";
    HET_Export.saveToOBJWithFaceColor(mesh, path, "test_color");
    //HET_Export.saveToWRLWithFaceColor(mesh,path, "test_color");
    println("model saved: " + path);
  }
}

```
Here is the screen capture, the white mesh is the reloaded, the colored boxes are the origional. By the way, from the screen capture, we can see the reloaded mesh, the color is missing, is this normal?
In the meantime, `HET_Export.saveToWRLWithFaceColor(mesh,path, "test_color");` is giving me errors.

![image](https://cloud.githubusercontent.com/assets/25093538/23584257/b61c0f52-0196-11e7-91c2-0711383ee629.png)

**Comment by bizkitj** [comment]
update: even after rotate the exported obj around x axis, the position of each box is still incorrect.
See attached screen capture.
![image](https://cloud.githubusercontent.com/assets/25093538/23584910/2f50843a-01aa-11e7-8f5e-78d2fbcc341a.png)

**Comment by wblut** [comment]
* HE_Mesh doesn't support importing color information. I might consider adding this later.
* Processing's coordinate system is left-handed (because of emphasis on 2D) and the Y axis is flipped compared to "normal" 3D right-handed convention. MeshLab, Blender, etc... are right-handed and will show the mesh flipped over the Y-axis. Using scale(1,-1,1) in Processing is the easiest way to make this consistent.
* I've run the tests here and import/export are consistent, no mesh flipping... However, in your code you need to reload objLoaded after saving the current mesh, otherwise you are comparing two differenr meshes (random z position).

`void keyPressed() {
  if (key=='s') {
    final String path = "d:/";
    HET_Export.saveToOBJWithFaceColor(mesh, path, "test_color");
    //HET_Export.saveToWRLWithFaceColor(mesh,path, "test_color");
      HEC_FromOBJFile obj = new HEC_FromOBJFile(
    "D:/test_color.obj");
  objLoaded = new HE_Mesh(obj);
    println("model saved: " + path);
  }
}`
