### ISSUE TITLE
Merging different meshes into a single one

### ISSUE THREAD

**Issue by op-rt** [wblut/HE_Mesh#6]
Dear @wblut ,

The title says it pretty much, I would like to merge 2 different shapes/meshes or more into one single mesh. Is it possible with Hemesh ?

I was thinking `HET_MeshOp.getFurthestIntersection()` or `WB_GeometryOp.getIntersection3D()` combined with `HEM_TriSplit.splitFaceTri()` could to the trick but my attempts have been unsuccessful so far.

Would really appreciate to have your lights on this.

**Comment by wblut** [comment]
Boolean operations aren't supported and cannot be implemented easily with methods exposed by hemesh.

**Comment by op-rt** [comment]
Alright, thank you for the swift reply.
