### ISSUE TITLE
problem copying a surface mesh from voronoi cell creation of 3d model

### ISSUE THREAD

**Issue by nosarious** [wblut/HE_Mesh#72]
Scenario is, start with a 3d object. Create voronoi, but only the surfaces. Copy a cell and validate. validation will fail.

`// generate voronoi cells
  HEMC_VoronoiCells multiCreator=new HEMC_VoronoiCells();
  multiCreator.setPoints(thesePoints);
  // alternatively points can be WB_Point[], any Collection<WB_Point> and double[][];
  multiCreator.setN(thesePoints.size()/2);
  multiCreator.setContainer(thisNewMesh);
  multiCreator.setOffset(3);
  multiCreator.setSurface(true);// is container mesh a volume (false) or a surface (true)
  multiCreator.setCreateSkin(false);
  multiCreator.setSimpleCap(bSimple);
  multiCreator.setBruteForce(true);
  cells=multiCreator.create();

HE_Mesh thisNewMesh= new HE_Mesh();
thisNewMesh = cells.getMesh(0);

render.drawFacesFC(thisNewMesh);
`

this will fail with 'NullPointerException' at the render line

**Comment by wblut** [comment]
Is the 3d object itself a valid 2-manifold, i.e. a mesh representable by the halfedge datastructure? Use "mesh.validate()" to check. It should show no errors (except boundary edges in an open mesh).

(Not sure about you using a local variable thisNewMesh with the same name as the global container mesh thisNewMesh. Seems like a good way to get confused.)

**Comment by nosarious** [comment]
ah. very good observation re:thisNewMesh. I copied bits of two functions which both receive a mesh called 'thisNewMesh'. I hope this code makes more sense. (edit: I found a better way to describe the problem which does not require any other code, but will leave this here for clarity)


if I copy a mesh returned from a voronoi surface creation, validation will fail:
'
  HE_Mesh thisCellMesh;
  thisCellMesh = firstCells.getMesh(thisNumber).get(); //new copy of cell surface
  thisCellMesh.validate(); //returns several 'Null reference (face) in half edge  <number>'
'


-this code included as reference.
`
void createObject(){
  firstShape = new HE_Mesh();
  firstShape = createARock(points);
  firstShape.moveToSelf(centerPoint);
  firstCells = createVoro(firstShape);
  thisNumber = int(random(0,firstCells.size()));
  rescaleSurface(firstCells.getMesh(thisNumber));
}

HE_Mesh createARock( float[][] points){
  print("starting rock formation ");
  HE_Mesh thisMesh;
  HEC_ConvexHull creator=new HEC_ConvexHull();
  creator.setPoints(points);
  creator.setN(10); 
  thisMesh = new HE_Mesh(creator); 
  println("rock is formed.");
  return thisMesh;
}

HE_MeshCollection createVoro(HE_Mesh outerShape){
  HE_Mesh thisNewMesh = new HE_Mesh();
  thisNewMesh = outerShape.get();
  
  HE_MeshCollection cells;
  // generate voronoi cells
  HEMC_VoronoiCells multiCreator=new HEMC_VoronoiCells();
  multiCreator.setPoints(thesePoints);
  multiCreator.setN(thesePoints.size()/2);/
  multiCreator.setContainer(thisNewMesh);
  multiCreator.setSurface(true);// is container mesh a volume (false) or a surface (true)
  return cells;
}

HE_Mesh rescaleSurface(HE_Mesh thisMesh){
  thisMesh.validate(); ///returns several 'Null reference (face) in half edge  <number>'
  HE_Mesh thisSurfaceMesh = new HE_Mesh();
  thisSurfaceMesh = thisMesh.get();
  thisSurfaceMesh.scaleSelf(0.5);
  println("rescaled a mesh");
  return thisSurfaceMesh;
}

`

**Comment by wblut** [comment]
Yes, those messages are normal. The outer halfedges of a surface have no associated face. Or in other words the boundary edges have only 1 face attached, not two like the other edges.

But this should not cause the observed problem. I will try to reproduce it.

**Comment by wblut** [comment]
I cannot reproduce the problem. Are you sure the null pointer isn't simply referring to "render". I sometimes forget the "render=new WB_Render3D(this);" in my setup() and get lost chasing mesh problems...

**Comment by nosarious** [comment]
this was a PEBKAC problem. an old code segment referring to a variable which was not initialized.

for reference: PEBKAC = "problem exists between keyboard and chair"
