### ISSUE TITLE
ability to check if point is in mesh?

### ISSUE THREAD

**Issue by mmmbop01** [wblut/HE_Mesh#76]
hello - is there a way to check if a point is located inside of a mesh? or a workaround for the older function **public boolean contains(final WB_Point3d p, final boolean isConvex)**?

note: this question comes from @AmnonOwed's generative typography w/ processing example on sphere packing

**Comment by wblut** [comment]
yes,

HET_MeshOp.isInside(mesh, p);

But if you want to check many points and the mesh doesn't change, this 
is a lot better:

WB_AABBTree tree=new WB_AABBTree(mesh,4);
HET_MeshOp.isInside(tree,p);



mmmbop01 schreef op 2017-08-23 01:48:

**Comment by mmmbop01** [comment]
this is great. thank you so much for your help :)
