### ISSUE TITLE
try/catch exceptions don't seem to be working.

### ISSUE THREAD

**Issue by nosarious** [wblut/HE_Mesh#77]
In both of these cases there are instances where the code will fail but the exception is not displayed 

i.e., shell doesn't work, yet "shell created" is displayed, smoothing doesn't work yet "smoothing completed" is displayed.stack trace never displayed, error messages never shown.

  ```
try{
    thisNewMesh.modify(new HEM_Shell().setThickness(-10));  
    println("shell created");
  } catch (final Exception ex) {
    //oops HE_Mesh messed up, retreat!
    ex.printStackTrace();
    println("unable to create shell");
  } 
  
  try{
    println("smoothing round one");
    thisNewMesh.subdivide(subdividor,2);//4 will make it slower to rotate
    println("smoothing complete");
  } catch (final Exception ex) {
    //oops HE_Mesh messed up, retreat!
    ex.printStackTrace();
    println("unable to smooth surfaces");
  }
```

**Comment by wblut** [comment]
In the latest version, modify(), subdivide() and simplify() encapsulate their own try/catch. If it fails, the original mesh is returned. So, your examples can never throw a Exception.
