### ISSUE TITLE
dodecahedron example references HEM_FaceExpandLS()

### ISSUE THREAD

**Issue by nosarious** [wblut/HE_Mesh#79]
HEM_FaceExpandLS has been changed to HEM_FaceExpand but not in this example.

 `mesh.modify(new HEM_FaceExpandLS().setDistance(10)); `
should be
 `mesh.modify(new HEM_FaceExpand().setDistance(10)); `

https://github.com/wblut/HE_Mesh/blob/master/examples/hemesh/create/Ref_HEC_Dodecahedron/Ref_HEC_Dodecahedron.pde

**Comment by wblut** [comment]
Yeah, that was messy, sorry.
