### ISSUE TITLE
extruded selection is no longer visible

### ISSUE THREAD

**Issue by nosarious** [wblut/HE_Mesh#81]
In the latest update some of my old code no longer works. For instance, selecting an extrusion which has been modified now says "the field HEM_Extrude.extruded is no longer visible"  

  HEM_Extrude modifier2 = new HEM_Extrude();
  modifier2.setDistance(40);// extrusion distance, set to 0 for inset faces
  modifier2.setRelative(false);// treat chamfer as relative to face size or as absolute value
  modifier2.setChamfer(10);// chamfer for non-hard edges
  modifier2.setHardEdgeChamfer(20);// chamfer for hard edges
  modifier2.setThresholdAngle(0.25*HALF_PI);// treat edges sharper than this angle as hard edges
  modifier2.setFuse(false);// try to fuse planar adjacent planar faces created by the extrude
  modifier2.setFuseAngle(0.05*HALF_PI);// threshold angle to be considered coplanar
  modifier2.setPeak(false);//if absolute chamfer is too large for face, create a peak on the face
  thisMesh.modify(modifier2);
  
  HE_Selection sel;
  sel=modifier2.extruded; //******* this line no longer works

**Comment by wblut** [comment]
Yes, that's why the major version jumped to 6.
Selections work differently and are now named objects inside each mesh.
Modifiers no longer expose public HE_Selection objects, but create selections inside the resulting mesh. Use mesh.getSelection("extruded") after a HEM_Extrude.

**Comment by nosarious** [comment]
Thank you very much. I noticed some changes with WB_SimpleCoordinate4D as well...
