### ISSUE TITLE
He_Mesh6.1.0: Tut006_Mesh_Selection in tutorial folder can not work because of the constructor HE_Selection(HE_Mesh) is not visible

### ISSUE THREAD

**Issue by lymanzhang** [wblut/HE_Mesh#82]
I updated to He_Mesh 6.1.0, but Tut006_Mesh_Selection can not work because of the constructor HE_Selection(HE_Mesh) is not visible. (He_Mesh 6.1.0, 2017.12.11)

Is there a new way to define a selection?
......
box=new HE_Mesh(boxCreator);
  //define a selection
  selection=new HE_Selection(box);  //this code can not wok
......

**Comment by nosarious** [comment]
from what I saw, the random face selection process is now in the HE_Mesh itself (going from the documentation)

Instead of 'selection=new HE_Selection(box);' try
`HE_Selection selection = box.selectRandomFaces("faces",0.5);`

and comment out the face selection process.
```
/*
  //add faces to selection 
  HE_FaceIterator fItr=box.fItr();
  HE_Face f;
  while (fItr.hasNext ()) {
    f=fItr.next();
    if (random(100)<50) selection.add(f);
  }
  */
```

**Comment by lymanzhang** [comment]
Hi nosarious, thank you for your comments. It now works for me well.

**Comment by wblut** [comment]
6.1.1. reintroduces "selection=new HE_Selection(mesh);", because sometime it's just convenienet and you don't need to keep track of the selection.
