### ISSUE TITLE
cannot apply a texture to more complicated objects.

### ISSUE THREAD

**Issue by nosarious** [wblut/HE_Mesh#83]
I wanted to apply a texture to a complicated model but cannot seem to do so. I basically changed the 'case 6' scenario in the Ref_Texture example to a HEC_ConvexHull creator. 

```
case 6:
    /*
    HEC_SuperDuper creator6=new HEC_SuperDuper();
    creator6.setU(64);
    creator6.setV(8);
    creator6.setUWrap(true);
    creator6.setVWrap(false); 
    creator6.setRadius(50);
    creator6.setDonutParameters(0, 10, 10, 10, 5, 6, 12, 12, 3, 1);
    */
    
    float[][] points;
    float objectRadius = 400;
    points =new float[500][3];
    for (int i=0;i<12;i++) {
      float r = objectRadius;// + random(0.01f)-100;
      float phi = radians(random(-90, 90));
      float theta = radians(random(360));
      points[i][0] = r*cos(phi)*cos(theta);
      points[i][1] = r*sin(phi);
      points[i][2] = r*cos(phi)*sin(theta);
    }
    HEC_ConvexHull creator6=new HEC_ConvexHull();
    
    creator6.setPoints(points);
    mesh=new HE_Mesh(creator6); 
    mesh.validate();
    break;
  }
```

I'm not sure if there is something I am missing here. I tried applying a simplifier to a mesh  mesh.simplify(new HES_TriDec().setGoal(0.5));  and also a catmull subdivider to see if it was related to how many times a mesh is adjusted, but it seems to be irrelevant.

I suspect there is a problem with the way the convex hull is created? Because it isn't symmetrical or something?

**Comment by wblut** [comment]
You'll need to roll your own texture coordinates, moset creators only assign (0,0) to the vertex texture coordinates. So your entire mesh is the color of the upperleft pixel of your texture.
Use vertex.setUVW(WB_coord) for a vertex texture coordinate independent of face and vertex.setUVW(WB_Coord, HE_Face) for a vertex coordinate in a specific face (for wrapping boundaries and such).
HEC_SuperDuper is a 2D (u,v) parametrization and defines its own texture coordinates in a natural way.
