### ISSUE TITLE
'mesh.selectRandomFaces' sometimes causes 'NoSuchElementException' error.

### ISSUE THREAD

**Issue by nosarious** [wblut/HE_Mesh#84]
If I use the following code on a mesh to delete random faces, I will sometimes get a 'NoSuchElementException' error on the line with delete faces. this makes me cry.

```
HE_Selection thisSelection;
thisSelection = mesh.selectRandomFaces("meshes",0.5); 
mesh.deleteFaces(thisSelection);
```

I also tried "faces",0.5 and "",0.5. available names are kind of unclear. I also tried using a seed (1234) and while I had more success, I still got zero faces selected occasionally.

**Comment by wblut** [comment]
Fixed in the latest version.
