### ISSUE TITLE
hemesh version 6.1.1: Something wrong with saveToSTL() 

### ISSUE THREAD

**Issue by lymanzhang** [wblut/HE_Mesh#86]
I just encountered faces lost asI checked the stl output using Meshlab. The stl output is generated by calling saveToSTL() to export mesh into stl. The version of HeMesh lib is 6.1.1. 

`HET_Export.saveToSTL(MESH, sketchPath(""),"export");`

processing snapshot.
![lostfaces_hemesh6 1 1](https://user-images.githubusercontent.com/4714220/34258238-0b537438-e698-11e7-83aa-6fc7c3b1c8a9.JPG)

meshlab snapshot.
![lostfaces2_hemesh6 1 1](https://user-images.githubusercontent.com/4714220/34258240-0c56bcbe-e698-11e7-982a-9fdb7f501770.JPG)

**Comment by wblut** [comment]
Triangulate before exporting. STL only supports triangles.

**Comment by lymanzhang** [comment]
thanks, I'll try that.

**Comment by lymanzhang** [comment]
Yes, it works. Thanks a lot!
