### ISSUE TITLE
cannot make a consistent 'stack' of planes.

### ISSUE THREAD

**Issue by nosarious** [wblut/HE_Mesh#97]
I am trying to make a 'stack' of planes that I can use to make contour lines of a model.

If I am creating the plane as:

```
for (int i= 0; i<numPlanes; i++){
    int otherPoint = i*10;
    Planes[i]=new WB_Plane(0,otherPoint,0,1,otherPoint,1); 
  }
```

I "should" get a stack of planes which are parallel to each other.

Instead, some planes seem to get skewed in the middle.

I have included a sample of what is happening. If you could take a peek and hit me with a clue-bat, that would be great.

```
import wblut.math.*;
import wblut.processing.*;
import wblut.core.*;
import wblut.hemesh.*;
import wblut.geom.*;

WB_Plane[] Planes;
int numPlanes;

WB
```_Render render;

void setup(){
    size(1920,1080,P3D);
    
    numPlanes = 50;
    
  Planes = new WB_Plane[numPlanes];
  
  for (int i= 0; i<numPlanes; i++){
    int otherPoint = (i*10)-200; //seems to be most noticeable when zero is in the middle
    Planes[i]=new WB_Plane(0,otherPoint,0,1,otherPoint,1); 
  }
  
   render=new WB_Render(this);
}


void draw(){
  background(255);

  translate(width/2, height/2,-300);
  directionalLight(255, 255, 255, 1, 1, -1);
  directionalLight(127, 127, 127, -1, -1, 1);
  lights();
  //rotateY(rotateStep);
  rotateY(mouseX*1.0f/width*TWO_PI);
  rotateX(mouseY*1.0f/height*TWO_PI);
  
  for(int i=0;i<numPlanes;i++){
    render.drawPlane(Planes[i],400);
  }
  
}

**Comment by nosarious** [comment]
Ah. thank you. I shall fix that.

I thought it was two points "on" the plane that were used to define the plane...

**Comment by wblut** [comment]
That would require 3 points. There's an infinite number of planes going through every pair of distinct points.

**Comment by nosarious** [comment]
Thank you for your quick response. My attempts have succeeded.

I 'did' notice that if the first plane from a collection of planes fails to intersect a model, the HEM_MultiSliceSurface will fail. I shall do another issue with an example for demonstrating.
